# -*- coding: utf-8 -*-
"""Random_Forest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w3Ad955p3mxPWMxr5ybOlxN2dK_E14I1
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier,RandomForestRegressor
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error,accuracy_score,precision_score,recall_score,f1_score

from sklearn.datasets import load_breast_cancer
data=load_breast_cancer()
data

df=pd.DataFrame(data.data,columns=data.feature_names)
df



df.columns

df['target']=data.target

df['target'].value_counts()



df

x=df.drop('target',axis=1)

x

y=df['target']

y

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

x_train

model=RandomForestClassifier()
model.fit(x_train,y_train)

y_pred=model.predict(x_test)

y_pred

r2_score(y_test,y_pred)

mean_absolute_error(y_test,y_pred)

mean_squared_error(y_test,y_pred)



"""Random Tree Regressor"""

from sklearn.datasets import fetch_california_housing
data1=fetch_california_housing()
data1

df1=pd.DataFrame(data1.data,columns=data1.feature_names)

df1

df1['Target']=data1.target

df

x=df1.drop('Target',axis=1)

y=df1.Target

x

y

x1_train,x1_test,y1_train,y1_test=train_test_split(x,y,test_size=0.3,random_state=42)

x1_train

model=RandomForestRegressor()
model.fit(x1_train,y1_train)

y1_test

y_pred=model.predict(x1_test)

y_pred

model.score(x1_test,y1_test)

r2_score(y1_test,y_pred)

mean_absolute_error(y1_test,y_pred)

mean_squared_error(y1_test,y_pred)

